### PR TITLE
[CAO-19477] Added information regarding unsupported browser extensions

### PR DESCRIPTION
**Pull request by SerG-Y**
Added information regarding unsupported browser extensions

### CODE REVIEW

**Review by kelvingraddick — COMMENTED** [review]
@SerG-Y Looks good! Does this add a link to the side panel as well?

**Comment by SerG-Y** [comment]
@kelvingraddick yes, it adds automatically for the headers

**Review by kelvingraddick — APPROVED** [review]

**Comment by kelvingraddick** [comment]
Please review/merge as soon as you are able @cvoncina @acdickin

**Comment by kelvingraddick** [comment]
Please review/merge as soon as you are able @cvoncina @acdickin

**Review by cvoncina — APPROVED** [review]
Looks fine to me

**Pull request merged**
